### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lreading** [OWASP/sonarqube#26]
Would it be possible to include a license in the repo itself, or at least mention the license in the readme?

The OWASP website mentions that this is licensed under the Apache 2.0 license
https://www.owasp.org/index.php/OWASP_SonarQube_Project#tab=Main

Thanks!

**Comment by VinodAnandan** [comment]
@lreading sorry for the misleading information. As per the SonarQube license, we will have to keep the LGPL v3 license. I have updated the information.
